const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const marked = require('marked');

const edgePath = "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";

const css = `
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Sarabun:wght@300;400;500;600;700&display=swap');
@page {
  size: A4;
  margin: 20mm 15mm 20mm 15mm;
}
body {
  font-family: 'Sarabun', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
  color: #1e293b;
  line-height: 1.65;
  font-size: 14px;
  background: #ffffff;
  margin: 0;
  padding: 0;
}
h1 {
  font-size: 26px;
  color: #1d4ed8;
  border-bottom: 2px solid #3b82f6;
  padding-bottom: 8px;
  margin-top: 0;
}
h2 {
  font-size: 20px;
  color: #0f172a;
  margin-top: 28px;
  border-bottom: 1px solid #e2e8f0;
  padding-bottom: 6px;
}
h3 {
  font-size: 16px;
  color: #2563eb;
  margin-top: 20px;
}
p, li {
  color: #334155;
}
ul, ol {
  padding-left: 20px;
}
li {
  margin-bottom: 6px;
}
table {
  width: 100%;
  border-collapse: collapse;
  margin: 16px 0;
  font-size: 13px;
}
th, td {
  border: 1px solid #cbd5e1;
  padding: 10px 12px;
  text-align: left;
}
th {
  background-color: #f1f5f9;
  color: #0f172a;
  font-weight: 600;
}
tr:nth-child(even) {
  background-color: #f8fafc;
}
blockquote {
  background: #eff6ff;
  border-left: 4px solid #3b82f6;
  margin: 16px 0;
  padding: 12px 16px;
  color: #1e3a8a;
  border-radius: 0 8px 8px 0;
}
code {
  background: #f1f5f9;
  color: #dc2626;
  padding: 2px 6px;
  border-radius: 4px;
  font-family: monospace;
  font-size: 13px;
}
hr {
  border: none;
  border-top: 1px solid #e2e8f0;
  margin: 24px 0;
}
.footer {
  margin-top: 40px;
  padding-top: 10px;
  border-top: 1px dashed #cbd5e1;
  font-size: 12px;
  color: #64748b;
  text-align: center;
}
`;

function convert(mdFile, htmlFile, pdfFile, title) {
  console.log(`Reading ${mdFile}...`);
  const mdContent = fs.readFileSync(mdFile, 'utf8');
  const htmlBody = marked.parse(mdContent);
  const fullHtml = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>${css}</style>
</head>
<body>
  ${htmlBody}
  <div class="footer">Generated by Antigravity AI — Enterprise Project Tracking System Manual</div>
</body>
</html>`;
  fs.writeFileSync(htmlFile, fullHtml, 'utf8');
  console.log(`Generated HTML: ${htmlFile}`);
  
  console.log(`Converting to PDF using Microsoft Edge...`);
  const cmd = `"${edgePath}" --headless --print-to-pdf="${pdfFile}" "${htmlFile}"`;
  execSync(cmd, { stdio: 'inherit' });
  console.log(`Successfully generated PDF: ${pdfFile}\n`);
}

convert('USER_MANUAL_TH.md', path.resolve('USER_MANUAL_TH.html'), path.resolve('USER_MANUAL_TH.pdf'), 'คู่มือการใช้งานระบบ (ฉบับภาษาไทย)');
convert('USER_MANUAL_EN.md', path.resolve('USER_MANUAL_EN.html'), path.resolve('USER_MANUAL_EN.pdf'), 'Enterprise System Manual (English Edition)');
convert('DEPLOYMENT_GUIDE_TH.md', path.resolve('DEPLOYMENT_GUIDE_TH.html'), path.resolve('DEPLOYMENT_GUIDE_TH.pdf'), 'คู่มือการนำระบบขึ้นใช้งานจริง (Production Deployment Guide)');

